[2023-06-26 04:25:08,455] INFO WorkerSourceTask{id=my-source-connect-second-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:478)
[2023-06-26 04:25:09,300] INFO [Consumer clientId=consumer-connect-cluster-2, groupId=connect-cluster] Error sending fetch request (sessionId=1915289084, epoch=1580) to node 0: (org.apache.kafka.clients.FetchSessionHandler:481)
org.apache.kafka.common.errors.DisconnectException
[2023-06-26 04:25:09,300] INFO [Consumer clientId=consumer-connect-cluster-1, groupId=connect-cluster] Error sending fetch request (sessionId=201649289, epoch=1578) to node 0: (org.apache.kafka.clients.FetchSessionHandler:481)
org.apache.kafka.common.errors.DisconnectException
[2023-06-26 04:25:09,300] INFO [Consumer clientId=consumer-connect-cluster-3, groupId=connect-cluster] Error sending fetch request (sessionId=1973837208, epoch=1581) to node 0: (org.apache.kafka.clients.FetchSessionHandler:481)
org.apache.kafka.common.errors.DisconnectException
[2023-06-26 04:25:08,473] INFO [Worker clientId=connect-1, groupId=connect-cluster] Group coordinator localhost:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response.isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:904)
[2023-06-26 04:25:09,602] INFO WorkerSourceTask{id=my-source-connect-second-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:495)
[2023-06-26 04:25:09,673] INFO [Worker clientId=connect-1, groupId=connect-cluster] Discovered group coordinator localhost:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:847)
[2023-06-26 04:25:09,673] INFO [Worker clientId=connect-1, groupId=connect-cluster] Group coordinator localhost:9092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable.isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:904)
[2023-06-26 04:25:09,777] INFO [Worker clientId=connect-1, groupId=connect-cluster] Discovered group coordinator localhost:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:847)
[2023-06-26 04:25:09,783] INFO [Worker clientId=connect-1, groupId=connect-cluster] Attempt to heartbeat with Generation{generationId=5, memberId='connect-1-ccc8f09f-30b0-4df0-a7f6-434c0102aa88', protocol='sessioned'} and group instance id Optional.empty failed due to UNKNOWN_MEMBER_ID, resetting generation (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:1121)
[2023-06-26 04:25:09,786] INFO [Worker clientId=connect-1, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:225)
[2023-06-26 04:25:09,786] INFO [Worker clientId=connect-1, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:540)
[2023-06-26 04:25:09,790] INFO [Worker clientId=connect-1, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:540)
[2023-06-26 04:25:09,792] INFO [Worker clientId=connect-1, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=7, memberId='connect-1-fa9705ad-2d3a-45b1-9666-f100e6cb91f1', protocol='sessioned'} (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:596)
[2023-06-26 04:25:09,802] INFO [Worker clientId=connect-1, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=7, memberId='connect-1-fa9705ad-2d3a-45b1-9666-f100e6cb91f1', protocol='sessioned'} (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:756)
[2023-06-26 04:25:09,803] INFO [Worker clientId=connect-1, groupId=connect-cluster] Joined group at generation 7 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-1-fa9705ad-2d3a-45b1-9666-f100e6cb91f1', leaderUrl='http://218.38.137.28:8083/', offset=6, connectorIds=[my-source-connect-second], taskIds=[my-source-connect-second-0], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1689)
[2023-06-26 04:25:09,804] WARN [Worker clientId=connect-1, groupId=connect-cluster] Catching up to assignment's config offset. (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1095)
[2023-06-26 04:25:09,806] INFO [Worker clientId=connect-1, groupId=connect-cluster] Current config state offset 4 is behind group assignment 6, reading to end of config log (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1158)
[2023-06-26 04:25:10,179] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished reading to end of log and updated config snapshot, new config log offset: 6 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1162)
[2023-06-26 04:25:10,179] INFO [Worker clientId=connect-1, groupId=connect-cluster] Starting connectors and tasks using config offset 6 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1216)
[2023-06-26 04:25:10,180] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1244)
[2023-06-26 04:25:19,656] INFO WorkerSourceTask{id=my-source-connect-second-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:478)
[2023-06-26 04:25:19,656] INFO WorkerSourceTask{id=my-source-connect-second-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:495)
